### PR TITLE
Allow Rails 5 and test with it

### PR DESCRIPTION
**Pull request by rafaelfranca**

### CODE REVIEW

**Comment by wvanbergen** [comment]
It does not seem to like Rails5 in the test suite.

**Comment by kirs** [comment]
I'll work on getting it green.

**Comment by wvanbergen** [comment]
I've added @rafaelfranca and @kirs as collaborators, go crazy!

**Comment by kirs** [comment]
Thanks!
My plan is:
1. Merge the PR and allow 5.0 builds to fail
2. Prepare a PR that makes 5.0 green
3. Push it :rocket:

**Pull request merged**
