### PR TITLE
Drop testing old rubies on Travis

### PR DESCRIPTION
**Pull request by kirs**
@wvanbergen

### CODE REVIEW

**Comment by wvanbergen** [comment]
:+1:

**Comment by rafaelfranca** [comment]
:+1:

**Comment by rafaelfranca** [comment]
Btw, before we doing this I think we should create a stable branch based in d6b3e1ef789fd2ece990daf20b1abcb1545a59a9 and release it.

**Comment by kirs** [comment]
Thanks for advise! I released 0.2.5.

**Pull request merged**
